---
language: cpp

matrix:
  include:
    - script:
        - uname -a
        - echo "Hello arm64 on branch $FLATPAK_BRANCH"
      os: Linux
      dist: focal
      arch: arm64
      env:
        - OCPN_TARGET=flatpak-arm64
        - FLATPAK_BRANCH=beta

branches:
  only:
    - master
    - build
