---
clone_folder: c:\project\opencpn\plugin_src
shallow_clone: false
clone_depth: 10

image:
  - Visual Studio 2022

platform:
  - Win32

configuration: RelWithDebInfo
test: false

before_build:
  - git submodule update --init opencpn-libs

build_script:
  - call ci\appveyor.bat
