---
version: 2
jobs:
  build-mingw:
    machine:
      image: circleci/classic:201808-01
    environment:
      - OCPN_TARGET:  mingw
    steps:
      - checkout
      - run: pyenv local 3.6.5
      - run: ci/circleci-build-mingw.sh
      - run: cd build; /bin/bash < upload.sh

  build-flatpak:
    machine:
      image: circleci/classic:201808-01
    environment:
      - OCPN_TARGET:  flatpak
    steps:
      - checkout
      - run: pyenv local 3.6.5
      - run: ci/circleci-build-flatpak.sh
      - run: cd build; /bin/bash < upload.sh

  build-macos:
    macos:
      xcode: "10.0.0"
    environment:
      - OCPN_TARGET:  macos
    steps:
      - checkout
      - run: ci/circleci-build-macos.sh
      - run: cd build; /bin/bash < upload.sh

  build-xenial:
    docker:
      - image: circleci/buildpack-deps:xenial-scm
    environment:
      - OCPN_TARGET:  xenial
    steps:
      - checkout
      - run: cat /etc/apt/sources.list
      - run: ci/circleci-build-debian.sh
      - run: cd build; /bin/bash < upload.sh

  build-bionic:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    environment:
      - OCPN_TARGET:  bionic
    steps:
      - checkout
      - run: cat /etc/apt/sources.list
      - run: ci/circleci-build-debian.sh
      - run: cd build; /bin/bash < upload.sh

  build-bionic-gtk3:
        docker:
        - image: circleci/buildpack-deps:bionic-scm
        environment:
        - BUILD_GTK3: true
        - OCPN_TARGET:  bionic-gtk3
        steps:
        - checkout
        - run: ci/circleci-build-debian.sh
        - run: cd build; /bin/bash < upload.sh

  build-focal:
    docker:
      - image: circleci/buildpack-deps:focal-scm
    environment:
      - OCPN_TARGET:  focal
      - BUILD_GTK3: true
    steps:
      - checkout
      - run: cat /etc/apt/sources.list
      - run: ci/circleci-build-debian.sh
      - run: cd build; /bin/bash < upload.sh

  build-buster:
    docker:
      - image: circleci/buildpack-deps:buster-scm
    environment:
      - OCPN_TARGET: buster
    steps:
      - checkout
      - run: ci/circleci-build-debian.sh
      - run: cd build; /bin/bash < upload.sh

  build-armhf-stretch:
    machine: true
    environment:
      - OCPN_TARGET=stretch-armhf
      - DOCKER_IMAGE=jongough/raspbian-stretch:latest
    steps:
      - checkout
      - run: pyenv local 3.5.2
      - run:
          command: ci/circleci-build-raspbian-armhf.sh
          no_output_timeout: 30m
      - run: cd build; /bin/bash < upload.sh

  build-armhf-buster:
    machine: true
    environment:
      - OCPN_TARGET=buster-armhf
      - DOCKER_IMAGE=jongough/raspbian-buster:plugin_build_tooling_current
    steps:
      - checkout
      - run: pyenv local 3.5.2
      - run:
          command: ci/circleci-build-raspbian-armhf.sh
          no_output_timeout: 30m
      - run: cd build; /bin/bash < upload.sh


workflows:
  version: 2
  build_all:
    jobs:
      - build-mingw:
          filters:
            branches:
              only:
                  - master
                  - build
      - build-flatpak:
          filters:
            branches:
              only:
                  - master
                  - build
      - build-macos:
          filters:
            branches:
              only:
                  - master
                  - build

      - build-xenial:
          filters:
            branches:
              only:
                  - master
                  - build

      - build-bionic-gtk3:
          filters:
            branches:
              only:
                  - master
                  - build

      - build-bionic:
          filters:
            branches:
              only:
                  - master
                  - build

      - build-focal:
          filters:
            branches:
              only:
                  - master
                  - build

      - build-buster:
          filters:
            branches:
              only:
                  - master
                  - build

      - build-armhf-stretch:
          filters:
            branches:
              only:
                  - master
                  - build


      - build-armhf-buster:
          filters:
            branches:
              only:
                  - master
                  - build
