---
name: build
on:
  push:
    branches:
      - ga

env:
  # Key for upload write access to  cloudsmith repo
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

  # git-push setup
  GIT_REPO: ${{ secrets.GIT_REPO }}
  GIT_KEY_PASSWORD: ${{ secrets.GIT_KEY_PASSWORD }}

  # Custom Cloudsmith repos instead of hardcoded defaults in Plugin.cmake
  CLOUDSMITH_UNSTABLE_REPO: ${{ secrets.CLOUDSMITH_UNSTABLE_REPO }}
  CLOUDSMITH_STABLE_REPO: ${{ secrets.CLOUDSMITH_STABLE_REPO }}
  CLOUDSMITH_BETA_REPO: ${{ secrets.CLOUDSMITH_BETA_REPO }}

jobs:
  flatpak-x86_64:
    runs-on: ubuntu-20.04
    env:
      OCPN_TARGET: flatpak-x86_64
      CMAKE_BUILD_PARALLEL_LEVEL: 2
    steps:
      - uses: actions/checkout@v2

      - name: Patch manifest to use correct branch
        run: >
          sed -i '/branch:/s/:.*/: ga/' \
              flatpak/org.opencpn.OpenCPN.Plugin.shipdriver.yaml

      - name: Build Flatpak aarch64
        run: ci/circleci-build-flatpak.sh

      - name: Upload tarball
        run: cd build; /bin/bash < upload.sh

      - name: Upload metadata
        run: python3 ci/git-push
