name: ShipDriver

on: push

jobs: 
  build:
    name: build-shipdriver
    runs-on: ubuntu-latest
    env:
      OCPN_TARGET: flatpak
      GIT_REPO: ${{ secrets.GIT_REPO}}
      GIT_KEY_PASSWORD: ${{ secrets.GIT_KEY_PASSWORD}}
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY}}
      CLOUDSMITH_STABLE_REPO: ${{ secrets.CLOUDSMITH_STABLE_REPO}}
      CLOUDSMITH_UNSTABLE_REPO: ${{ secrets.CLOUDSMITH_UNSTABLE_REPO}}
      CLOUDSMITH_BETA_REPO: ${{ secrets.CLOUDSMITH_BETA_REPO}}

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Do-build
        run: |
          ci/github-build-flatpak.sh
          sh -c "ldd  build/app/*/lib/opencpn/*.so"

      - name: Upload
        run: |
          sh -c "cd build; /bin/bash < upload.sh"
          python3 ci/git-push
